-- Enable pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- Tickets: incoming support requests
CREATE TABLE IF NOT EXISTS tickets (
    id SERIAL PRIMARY KEY,
    source_email TEXT NOT NULL,
    subject TEXT NOT NULL,
    body TEXT NOT NULL,
    type TEXT,          -- billing, technical, feature_request, escalation, general
    urgency TEXT,       -- low, medium, high
    status TEXT NOT NULL DEFAULT 'pending',  -- pending, approved, sent
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Pipeline run stages per ticket
CREATE TABLE IF NOT EXISTS pipeline_runs (
    id SERIAL PRIMARY KEY,
    ticket_id INTEGER NOT NULL REFERENCES tickets(id) ON DELETE CASCADE,
    stage TEXT NOT NULL,    -- classify, search, draft
    status TEXT NOT NULL,   -- running, completed, failed
    duration_ms INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pipeline_runs_ticket_id ON pipeline_runs(ticket_id);

-- Knowledge base chunks with embeddings
CREATE TABLE IF NOT EXISTS kb_chunks (
    id SERIAL PRIMARY KEY,
    document_name TEXT NOT NULL,
    chunk_text TEXT NOT NULL,
    embedding vector(384),  -- BAAI/bge-small-en-v1.5 outputs 384 dims
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_kb_chunks_embedding ON kb_chunks USING ivfflat (embedding vector_cosine_ops)
    WITH (lists = 10);

-- Draft responses generated by LLM
CREATE TABLE IF NOT EXISTS draft_responses (
    id SERIAL PRIMARY KEY,
    ticket_id INTEGER NOT NULL REFERENCES tickets(id) ON DELETE CASCADE,
    draft_text TEXT NOT NULL,
    sources_used JSONB NOT NULL DEFAULT '[]',
    confidence_score FLOAT,
    approved_by TEXT,
    sent_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_draft_responses_ticket_id ON draft_responses(ticket_id);

-- Email delivery log
CREATE TABLE IF NOT EXISTS delivery_log (
    id SERIAL PRIMARY KEY,
    ticket_id INTEGER NOT NULL REFERENCES tickets(id) ON DELETE CASCADE,
    recipient_email TEXT NOT NULL,
    status TEXT NOT NULL,   -- sent, failed
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Webhook events received
CREATE TABLE IF NOT EXISTS webhook_events (
    id SERIAL PRIMARY KEY,
    payload_hash TEXT NOT NULL,
    signature_valid BOOLEAN NOT NULL,
    raw_payload JSONB,
    processed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    pipeline_run_id INTEGER REFERENCES pipeline_runs(id)
);
